BillDash/urls.py
from . import views
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("", views.index, name="index"),
    path("bills", views.bills, name="bills"),
    path("viewbill/<int:bill_no>/", views.view_bill, name="view_bill"),
    path("paybill/<int:bill_no>/", views.pay_bill, name="pay_bill"),
    path("serverinfo/<int:server_id>/", views.server_info, name="server_info"),
]

IvyBill/urls.py
import django
from django.contrib import admin
from django.urls import path, include
import BillDash

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("BillDash.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

BillDash/models.py
from typing_extensions import Required
from django.contrib import admin
from django.db import models
from django.contrib.auth.models import User
from .pterodactyl import Pterodactyl
import json
from . import notify
from django.utils import timezone

from BillDash import pterodactyl

pterodactyl = Pterodactyl(
    json.load(open("secrets.json"))["pterodactyl_token"],
    json.load(open("secrets.json"))["pterodactyl_url"],
)

# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(
        User, null=True, blank=True, on_delete=models.PROTECT, default=None
    )
    name = models.CharField(max_length=25)
    ptero_id = models.IntegerField(blank=True, null=True, default=None)

    def __str__(self) -> str:
        return self.name

    def email(self):
        return self.user.email

    def save(self, *args) -> None:
        if self.ptero_id is not None:
            return super().save(*args)
        res = pterodactyl.create_new_user(
            self.user.email,
            self.user.username,
            self.user.first_name,
            self.user.last_name,
        )
        if res is None:
            return print("Error creating customer")
        self.ptero_id = int(res["attributes"]["id"])
        return super().save(*args)

    def delete(self, *args):
        if pterodactyl.delete_user(self.ptero_id):
            return super().delete(*args)
        return print("Error deleting customer")


class Bill(models.Model):
    bill_number = models.AutoField(primary_key=True)
    server = models.ForeignKey("Server", on_delete=models.SET_NULL, null=True)
    currency = models.CharField(max_length=3)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    creation_date = models.DateTimeField(auto_now_add=True)
    due_date = models.DateTimeField()
    paid = models.BooleanField(default=False)

    def __str__(self) -> str:
        try:
            return f"{self.server.customer} - {self.due_date.isoformat()}"
        except:
            return f"{self.server} - {self.due_date.isoformat()}"

    def save(self, *args) -> None:
        if (not self._state.adding) and self.paid:
            self.server.next_payment_date += timezone.timedelta(days=30)
            if self.server.suspended:
                self.server.suspended = False
                self.server.save()
            notify.bill_paid(self)
            return super().save(*args)
        if self.amount > 0:
            notify.new_bill(self)
            return super().save(*args)
        self.amount = self.server.plan.price
        notify.new_bill(self)
        return super().save(*args)
    
    def delete(self, *args):
        notify.bill_delete(self)
        return super().delete(*args)


class Location(models.Model):
    name = models.CharField(max_length=25)
    ptero_id = models.IntegerField(blank=True, null=True, default=None)

    def __str__(self) -> str:
        return self.name


class Plan(models.Model):
    ram = models.IntegerField(default=0)
    cpu = models.IntegerField(default=0)
    disk = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    name = models.CharField(max_length=25)
    network_allocations = models.IntegerField(default=1)
    backups = models.IntegerField(default=0)
    databases = models.IntegerField(default=0)
    location = models.ForeignKey(Location, on_delete=models.PROTECT, default=None)
    dedicated_ip = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class ServerSoftware(models.Model):
    name = models.CharField(max_length=25)
    game_name = models.CharField(max_length=25)
    ptero_nest_id = models.IntegerField(blank=False, null=False)
    ptero_egg_id = models.IntegerField(blank=False, null=False)
    docker_image = models.CharField(max_length=25, blank=True, null=True)
    startup_command = models.CharField(max_length=1000, blank=True, null=True)
    environment = models.CharField(max_length=1000, blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.game_name} - {self.name}"

    def save(self, *args) -> None:
        resp = pterodactyl.get_egg_info(self.ptero_nest_id, self.ptero_egg_id)
        if not resp:
            return "Error getting egg info"
        self.docker_image = resp["attributes"]["docker_image"]
        env = {}
        for var in resp["attributes"]["relationships"]["variables"]["data"]:
            env[f"{var['attributes']['env_variable']}"] = var["attributes"][
                "default_value"
            ]
        self.environment = json.dumps(env)
        self.startup_command = resp["attributes"]["startup"]
        return super().save(*args)


class Server(models.Model):
    server_id = models.IntegerField()
    server_id_hex = models.CharField(max_length=10, blank=True, null=True, default=None)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    creation_date = models.TimeField(auto_now=True)
    plan = models.ForeignKey(Plan, on_delete=models.PROTECT)
    next_payment_date = models.DateTimeField(null=True, blank=True)
    server_software = models.ForeignKey(
        ServerSoftware, on_delete=models.PROTECT, default=None
    )
    suspended = models.BooleanField(default=False)

    def __str__(self):
        return self.server_id_hex

    def name(self):
        res = pterodactyl.get_server_info(self.server_id)
        if not res:
            return "Error getting server info"
        return res["attributes"]["name"]

    def save(self, *args):
        if not self._state.adding:
            if not self.suspended:
                notify.unsuspend_server(self)
                pterodactyl.unsuspend_server(self.server_id)
            if self.suspended:
                notify.suspend_server(self)
                pterodactyl.suspend_server(self.server_id)
            return super().save(*args)
        if self.server_id is not None:
            self.server_id_hex = pterodactyl.get_server_info(self.server_id)[
                "attributes"
            ]["identifier"]
            return super().save(*args)
        specs = {
            "name": f"{self.customer.name}-{self.plan.name}",
            "user": self.customer.ptero_id,
            "egg": self.server_software.ptero_egg_id,
            "docker_image": self.server_software.docker_image,
            "startup": self.server_software.startup_command,
            "environment": json.loads(self.server_software.environment),
            "limits": {
                "memory": self.plan.ram,
                "swap": -1,
                "disk": self.plan.disk,
                "io": 500,
                "cpu": self.plan.cpu,
            },
            "feature_limits": {
                "databases": self.plan.databases,
                "backups": self.plan.backups,
                "allocations": self.plan.network_allocations,
            },
            "deploy": {
                "location": [self.plan.location.ptero_id],
                "dedicated_ip": self.plan.dedicated_ip,
            },
        }
        res = pterodactyl.create_new_server(
            specs["name"],
            specs["user"],
            specs["egg"],
            specs["docker_image"],
            specs["startup"],
            specs["environment"],
            specs["limits"],
            specs["feature_limits"],
            specs["deploy"]["location"],
            specs["deploy"]["dedicated_ip"],
        )
        if res == None:
            return print("Error creating server")
        self.server_id = res["attributes"]["id"]
        self.server_id_hex = res["attributes"]["identifier"]
        notify.new_server(self)
        return super().save(*args)

    def delete(self, *args):
        pterodactyl.delete_server(self.server_id)
        notify.delete_server(self)
        return super().delete(*args)

BillDash/views.py
import re
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.decorators import login_required

from BillDash.models import Bill, Server
from .pterodactyl import Pterodactyl
import json

# Create your views here.\
@login_required
def index(request: HttpRequest):
    secrets = json.load(open("secrets.json"))
    ptero_url = secrets["pterodactyl_url"]
    contents = {"ptero_url": ptero_url}
    return render(request, "BillDash/index.html", contents)


@login_required
def bills(request: HttpRequest):
    return render(request, "BillDash/bills.html")


@login_required
def view_bill(request: HttpRequest, bill_no: int):
    if not Bill.objects.get(pk=bill_no):
        return redirect("/")
    bill = Bill.objects.get(pk=bill_no)
    context = {"bill": bill}
    return render(request, "BillDash/view_bill.html", context)


@login_required
def pay_bill(request: HttpRequest, bill_no: int):
    if not Bill.objects.get(pk=bill_no):
        return redirect("/")
    bill = Bill.objects.get(pk=bill_no)
    if bill.paid:
        return redirect("view_bill", bill_no=bill_no)
    context = {"bill": bill}
    return render(request, "BillDash/pay_bill.html", context)


@login_required
def server_info(request: HttpRequest, server_id: int):
    if not Server.objects.filter(server_id=server_id).exists():
        return redirect("index")
    ptero = Pterodactyl(
        json.load(open("secrets.json"))["pterodactyl_token"],
        json.load(open("secrets.json"))["pterodactyl_url"],
    )
    server = ptero.get_server_info(server_id)
    context = {
        "ptero_server": server,
        "db_server": Server.objects.get(server_id=server_id),
        "ptero_url": json.load(open("secrets.json"))["pterodactyl_url"],
    }
    return render(request, "BillDash/server_info.html", context)

BillDash/templates/BillDash/base.html
<html>
    <head>
        <title>IvyBill {%block title%}{%endblock%}</title>
        <!-- google icons -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!-- materialize css -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
        <!-- bootstrap css -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>
        <div class="containter" align="center">
            <div class="row">
                <div class="col-md-3">
                    <h1>IvyBill</h1>
                    <hr>
                    {% if user %}
                        <small>Logged in as:</small>
                        <h4>Name: {{ user.first_name }} {{ user.last_name }}</h2>
                        <h4>Email: {{ user.email }}</h4>
                        <a href="{% url 'logout' %}"><button class="btn btn-danger">Logout</button></a>
                    {% else %}
                        <small>Not logged in</small>
                        <h2><a href="{% url 'login' %}">Login</a></h2>
                    {% endif %}
                    <hr>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="{% url 'index' %}">Home</a></li>
                    </ul>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="{% url 'bills' %}">Bills</a></li>
                    </ul>
                </div>
                <div class="col-md-9">
                    {%block content%}
                        <p>How even did you end up here?!</p>
                    {%endblock%}
                </div>
            </div>
        </div>
        <footer>
            <div class="container" align="center">
                <div class="row">
                    <div class="col-md-12">
                        <p>&copy; IvyBill 2022</p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap JS -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <!-- JQuery -->
        <script src="https://code.jquery.com/jquery-3.6.1.min.js" crossorigin="anonymous"></script>
    </body>
</html>

BillDash/templates/BillDash/bills.html
{% extends 'BillDash/base.html' %}

{% block title %} Bills {% endblock %}
{% block content %}
<div>
    <h1>Bills</h1>
    <hr>
    <h2>Your Bills</h2>
    <hr>
    <table class="table">
        <thead>
            <tr>
                <th>Bill Amount</th>
                <th>Bill Due Date</th>
                <th>Bill Creation Date</th>
                <th>Bill Status</th>
                <th>More Info</th>
            </tr>
        </thead>
        <tbody>
            {% for server in user.customer.server_set.all %}
            <div>
                <tr>
                    <td colspan=4 scope="colgroup">Server: {{ server.name }}</td>
                </tr>
                {% for bill in server.bill_set.all %}
                <tr>
                    <td>{{ bill.amount }} {{ bill.currency }}</td>
                    <td>{{ bill.due_date }}</td>
                    <td>{{ bill.creation_date }}</td>
                    <td>{{ bill.paid }}</td>
                    <td><a href="{% url 'view_bill' bill.pk %}"><button class="btn btn-info">View Bill</button></a></td>
                </tr>
                {% endfor %}
            </div>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

BillDash/templates/BillDash/index.html
{% extends 'BillDash/base.html' %}

{% block title %} Home {% endblock %}
{% block content %}
<div>
    <h1>Home</h1>
    <hr>
    <h2>Your Servers</h2>
    <hr>
    <table class="table">
        <thead>
            <tr>
                <th>Server Name</th>
                <th>Server Plan</th>
                <th>Server Software</th>
                <th>Panel link</th>
                <th>Manage Server</th>
            </tr>
        </thead>
        <tbody>
            {% for server in user.customer.server_set.all %}
            <tr>
                <td>{{ server.name }}</td>
                <td>{{ server.plan }}</td>
                <td>{{ server.server_software }}</td>
                <td><a href="{{ ptero_url }}/server/{{ server.server_id_hex }}"><button
                            class="btn btn-primary">Panel</button></a></td>
                <td><a href="{% url 'server_info' server.server_id %}"><button class="btn btn-info">More
                            Info</button></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

BillDash/templates/BillDash/pay_bill.html
{% extends 'BillDash/base.html' %}

{% block title %} Pay Bill {{bill.pk}} {% endblock %}
{% block content %}
<div>
    <h1>Paying for bill {{bill.pk}}</h1>
    <hr>
    <p><b>Bill Number:</b> {{bill.pk}}</p>
    <p><b>Bill Name:</b> {{bill}}</p>
    <p><b>Server:</b> {{bill.server}}</p>
    <p><b>Bill Amount:</b> {{bill.amount}} {{bill.curency}}</p>
    <p><b>Bill Geneation Date:</b> {{bill.creation_date}}</p>
    <p><b>Bill Due Date:</b> {{bill.due_date}}</p>
    <h2>Online Bill Payment system isn't implemented yet.</h2>
</div>
{% endblock %}

BillDash/templates/BillDash/server_info.html
{% extends 'BillDash/base.html' %}

{% block title %} Server {{db_server.server_id}} {% endblock %}
{% block content %}
<div>
    <h1>Server {{db_server.server_id}}</h1>
    <hr>
    <p><b>Server Name:</b> {{db_server.name}}</p>
    <p><b>Server Plan:</b> {{db_server.plan}}</p>
    <p><b>Server Location:</b> {{db_server.plan.location}}</p>
    <p><b>Server Software:</b> {{db_server.server_software}}</p>
    <p><b>Server Support Code:</b> {{db_server.server_id_hex}}</p>
    <p><b>Server Suspension Status:</b> {{ptero_server.attributes.suspended}}</p>
    <p><b>Server Specs:</b>
    <ul>
        <li>CPU: {{ptero_server.attributes.limits.cpu}} %</li>
        <li>RAM: {{ptero_server.attributes.limits.memory}} MiB</li>
        <li>Disk: {{ptero_server.attributes.limits.disk}} MiB</li>
    </ul>
    </p>
    <p><b>Server Features:</b>
    <ul>
        <li>Databses: {{ptero_server.attributes.feature_limits.databases}}</li>
        <li>Backups: {{ptero_server.attributes.feature_limits.backups}}</li>
    </ul>
    </p>
    <p><b>Network Allocations:</b> <br>
    <ul>
        {% for allocation in ptero_server.attributes.relationships.allocations.data %}
        <li>{{allocation.attributes.alias}}:{{allocation.attributes.port}}</li>
        {% endfor %}
    </ul>
    </p>
    <p>
        <b>Server Creation Date:</b> {{db_server.creation_date}}
    </p>
    <p>
        <b>Next Bill Due:</b> {{db_server.next_payment_date}}
    </p>
    <p><b>Server Bills: </b>
    <table class="table">
        <thead>
            <tr>
                <th>Bill Amount</th>
                <th>Bill Due Date</th>
                <th>Bill Creation Date</th>
                <th>Bill Status</th>
                <th>More Info</th>
            </tr>
        </thead>
        <tbody>
            {% for bill in db_server.bill_set.all %}
            <tr>
                <td>{{ bill.amount }} {{ bill.currency }}</td>
                <td>{{ bill.due_date }}</td>
                <td>{{ bill.creation_date }}</td>
                <td>{{ bill.paid }}</td>
                <td><a href="{% url 'view_bill' bill.pk %}"><button class="btn btn-info">View Bill</button></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </p>
    <p><a href="{{ ptero_url }}/server/{{ db_server.server_id_hex }}"><button class="btn btn-primary">Panel</button></a>
        <a href="{% url 'index' %}"><button class="btn btn-link">Back to Home</button></a>
    </p>
</div>
{% endblock %}

BillDash/templates/BillDash/view_bill.html
{% extends 'BillDash/base.html' %}

{% block title %} View Bill {{bill.pk}} {% endblock %}
{% block content %}
<div>
    <h1>Bill Info</h1>
    <hr>
    <p><b>Bill Number:</b> {{bill.pk}}</p>
    <p><b>Bill Name:</b> {{bill}}</p>
    <p><b>Server:</b> <a href="{% url 'server_info' bill.server.server_id %}">{{bill.server.name}}</a></p>
    <p><b>Bill Amount:</b> {{bill.amount}} {{bill.curency}}</p>
    <p><b>Bill Geneation Date:</b> {{bill.creation_date}}</p>
    <p><b>Bill Due Date:</b> {{bill.due_date}}</p>
    {% if bill.paid %}
    <p><b>Bill Status:</b> <span style="color: 00ff00;">Paid</span></p>
    {% else %}
    <p><b>Bill Status:</b> <span style="color: ff0000;">Unpaid</span></p>
    <p><a href="{% url 'pay_bill' bill.pk %}"><button class="btn btn-success">Pay Now!</button></a></p>
    {% endif %}
</div>
{% endblock %}